apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume
  template:
    metadata:
      labels:
        app: resume
    spec:
      containers:
      - name: resume
        image: ghcr.io/mike12806/resume:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: resume-service
spec:
  type: ClusterIP
  selector:
    app: resume
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
